import { expect } from '@jest/globals';

import { GetMediaInfoTestCase } from '../test-utils';

export const mediaUtilsTestCases: GetMediaInfoTestCase[] = [
  {
    filename: 'engine-start.aac',
    expectedMediaInfo: {
      bytesRead: 65536,
      audioStreams: [
        {
          id: 0,
          channelCount: 2,
          codec: 'aac',
          codecDetail: 'mp4a.40.2',
          sampleRate: 44100,
          profile: 'LC',
        },
      ],
      container: 'aac',
      containerDetail: 'aac',
      durationInSeconds: undefined,
      parser: 'media-utils',
      videoStreams: [],
    },
  },
  {
    filename: 'engine-start.mp3',
    expectedMediaInfo: {
      bytesRead: 65536,
      parser: 'media-utils',
      audioStreams: [
        {
          id: 0,
          bitrate: expect.closeTo(128273, -2) as any,
          channelCount: 2,
          codec: 'mp3',
          codecDetail: 'MPEG-1 Layer III',
          durationInSeconds: expect.closeTo(6, 0.1) as any,
          sampleRate: 44100,
          codecDetails: {
            layer: 3,
            padding: 0,
          },
        },
      ],
      container: 'mp3',
      containerDetail: 'mp3',
      durationInSeconds: expect.closeTo(6, 0.1) as any,
      videoStreams: [],
    },
  },
  {
    filename: 'engine-start.vp9.opus.webm',
    expectedMediaInfo: {
      bytesRead: 1371,
      audioStreams: [
        {
          id: 2,
          channelCount: 2,
          codec: 'opus',
          codecDetail: 'A_OPUS',
          durationInSeconds: 6.008,
          sampleRate: 48000,
          bitsPerSample: 32,
        },
      ],
      container: 'webm',
      containerDetail: 'webm',
      durationInSeconds: 6.008,
      parser: 'media-utils',
      videoStreams: [
        {
          id: 1,
          codec: 'vp9',
          codecDetail: 'V_VP9',
          durationInSeconds: 6.008,
          height: 534,
          width: 1280,
        },
      ],
    },
  },
  {
    filename: 'engine-start.vp8.vorbis.webm',
    expectedMediaInfo: {
      bytesRead: 10489,
      audioStreams: [
        {
          id: 2,
          channelCount: 2,
          codec: 'vorbis',
          codecDetail: 'A_VORBIS',
          durationInSeconds: 6.007,
          sampleRate: 48000,
          bitsPerSample: 32,
        },
      ],
      container: 'webm',
      containerDetail: 'webm',
      durationInSeconds: 6.007,
      parser: 'media-utils',
      videoStreams: [
        {
          id: 1,
          codec: 'vp8',
          codecDetail: 'V_VP8',
          durationInSeconds: 6.007,
          height: 534,
          width: 1280,
        },
      ],
    },
  },
  {
    filename: 'engine-start.vp9.vorbis.webm',
    expectedMediaInfo: {
      bytesRead: 8539,
      audioStreams: [
        {
          id: 2,
          channelCount: 2,
          codec: 'vorbis',
          codecDetail: 'A_VORBIS',
          durationInSeconds: 6.007,
          sampleRate: 48000,
          bitsPerSample: 32,
        },
      ],
      container: 'webm',
      containerDetail: 'webm',
      durationInSeconds: 6.007,
      parser: 'media-utils',
      videoStreams: [
        {
          id: 1,
          codec: 'vp9',
          codecDetail: 'V_VP9',
          durationInSeconds: 6.007,
          height: 534,
          width: 1280,
        },
      ],
    },
  },
  {
    filename: 'engine-start.av1.opus.webm',
    expectedMediaInfo: {
      bytesRead: 4279,
      audioStreams: [
        {
          id: 2,
          channelCount: 2,
          codec: 'opus',
          codecDetail: 'A_OPUS',
          durationInSeconds: 6.008,
          sampleRate: 48000,
          bitsPerSample: 32,
        },
      ],
      container: 'webm',
      containerDetail: 'webm',
      durationInSeconds: 6.008,
      parser: 'media-utils',
      videoStreams: [
        {
          id: 1,
          codec: 'av1',
          codecDetail: 'V_AV1',
          durationInSeconds: 6.008,
          height: 534,
          width: 1280,
        },
      ],
    },
  },
  {
    filename: 'engine-start.h264.aac.mp4',
    expectedMediaInfo: {
      bytesRead: 6050,
      parser: 'media-utils',
      container: 'mp4',
      containerDetail: 'isom, isom, iso2, avc1, mp41',
      durationInSeconds: expect.closeTo(6, 0) as any,
      videoStreams: [
        {
          codec: 'h264',
          codecDetail: 'avc1.64001f',
          durationInSeconds: expect.closeTo(6, 0) as any,
          id: 1,
          width: 1280,
          height: 534,
          fps: 24,
          bitrate: 349083,
        },
      ],
      audioStreams: [
        {
          codec: 'aac',
          codecDetail: 'mp4a.40.02',
          durationInSeconds: expect.closeTo(6, 0) as any,
          id: 2,
          sampleRate: 44100,
          bitrate: expect.closeTo(127930, -3) as any,
          channelCount: 2,
          profile: 'LC',
        },
      ],
    },
  },
  {
    filename: 'engine-start.h264.aac-mono.mp4',
    expectedMediaInfo: {
      bytesRead: 6042,
      parser: 'media-utils',
      container: 'mp4',
      containerDetail: 'isom, isom, iso2, avc1, mp41',
      durationInSeconds: expect.closeTo(6, 0) as any,
      videoStreams: [
        {
          codec: 'h264',
          codecDetail: 'avc1.64001f',
          durationInSeconds: expect.closeTo(6, 0) as any,
          id: 1,
          width: 1280,
          height: 534,
          fps: 24,
          bitrate: 349083,
        },
      ],
      audioStreams: [
        {
          codec: 'aac',
          codecDetail: 'mp4a.40.02',
          durationInSeconds: expect.closeTo(6, 0) as any,
          id: 2,
          sampleRate: 44100,
          bitrate: expect.closeTo(69701, -3) as any,
          channelCount: 1,
          profile: 'LC',
        },
      ],
    },
  },
  {
    filename: 'engine-start.h264.mp3.mp4',
    expectedMediaInfo: {
      bytesRead: 365336, // Atom mdat @ 40 of size: 358786, ends @ 358826, Atom moov @ 358826 of size: 6510, ends @ 365336
      parser: 'media-utils',
      container: 'mp4',
      containerDetail: 'isom, isom, iso2, avc1, mp41',
      durationInSeconds: expect.closeTo(6, 0) as any,
      videoStreams: [
        {
          codec: 'h264',
          codecDetail: 'avc1.64001f',
          durationInSeconds: expect.closeTo(6, 0) as any,
          id: 1,
          width: 1280,
          height: 534,
          fps: 24,
          bitrate: 349083,
        },
      ],
      audioStreams: [
        {
          codec: 'mp3',
          codecDetail: 'mp4a.6b',
          durationInSeconds: expect.closeTo(6, 0) as any,
          id: 2,
          sampleRate: 44100,
          bitrate: expect.closeTo(128452, -3) as any,
          channelCount: 2,
        },
      ],
    },
  },
  {
    filename: 'engine-start.h264.mp3-mono.mp4',
    expectedMediaInfo: {
      bytesRead: 317074,
      parser: 'media-utils',
      container: 'mp4',
      containerDetail: 'isom, isom, iso2, avc1, mp41',
      durationInSeconds: expect.closeTo(6, 0) as any,
      videoStreams: [
        {
          codec: 'h264',
          codecDetail: 'avc1.64001f',
          durationInSeconds: expect.closeTo(6, 0) as any,
          id: 1,
          width: 1280,
          height: 534,
          fps: 24,
          bitrate: 349083,
        },
      ],
      audioStreams: [
        {
          codec: 'mp3',
          codecDetail: 'mp4a.6b',
          durationInSeconds: expect.closeTo(6, 0) as any,
          id: 2,
          sampleRate: 44100,
          bitrate: expect.closeTo(64010, -3) as any,
          channelCount: 1,
        },
      ],
    },
  },
  {
    filename: 'engine-start.h264.aac.mov',
    expectedMediaInfo: {
      bytesRead: 810587, // moov after [mdat] size=805155
      parser: 'media-utils',
      container: 'mov',
      containerDetail: 'qt  , qt  ',
      durationInSeconds: expect.closeTo(6, 0) as any,
      videoStreams: [
        {
          codec: 'h264',
          width: 1280,
          height: 534,
          id: 1,
          codecDetail: 'avc1.4d401f',
          durationInSeconds: expect.closeTo(6, 0) as any,
          fps: expect.closeTo(22.1, 1) as any,
          bitrate: 939149,
        },
      ],
      audioStreams: [
        {
          codec: 'aac',
          id: 2,
          codecDetail: 'mp4a',
          channelCount: 2,
          sampleRate: 44100,
          bitrate: expect.closeTo(131692, -3) as any,
          durationInSeconds: expect.closeTo(6, 0) as any,
        },
      ],
    },
  },
  {
    filename: 'engine-start.h264.aac-mono.mov',
    expectedMediaInfo: {
      bytesRead: 769525,
      parser: 'media-utils',
      container: 'mov',
      containerDetail: 'qt  , qt  ',
      durationInSeconds: expect.closeTo(6, 0) as any,
      videoStreams: [
        {
          codec: 'h264',
          codecDetail: 'avc1.4d401f',
          durationInSeconds: expect.closeTo(6, 0) as any,
          id: 1,
          width: 1280,
          height: 534,
          fps: expect.closeTo(22, 0) as any,
          bitrate: 939149,
        },
      ],
      audioStreams: [
        {
          codec: 'aac',
          codecDetail: 'mp4a',
          durationInSeconds: expect.closeTo(6, 0) as any,
          id: 2,
          sampleRate: 44100,
          bitrate: expect.closeTo(76677, -3) as any,
          channelCount: 1,
        },
      ],
    },
  },
  {
    filename: 'engine-start.h264.mp3.mov',
    expectedMediaInfo: {
      bytesRead: 856055, // moov after [mdat] size=850251
      parser: 'media-utils',
      container: 'mov',
      containerDetail: 'qt  , qt  ',
      durationInSeconds: expect.closeTo(6, 0) as any,
      videoStreams: [
        {
          codec: 'h264',
          codecDetail: 'avc1.4d401f',
          id: 1,
          width: 1280,
          height: 534,
          durationInSeconds: expect.closeTo(6, 0) as any,
          fps: expect.closeTo(22, 0) as any,
          bitrate: expect.closeTo(939149, -4) as any,
        },
      ],
      audioStreams: [
        {
          codec: 'mp3',
          codecDetail: '.mp3',
          id: 2,
          channelCount: 2,
          sampleRate: 44100,
          bitrate: expect.closeTo(192000, -4) as any,
          durationInSeconds: expect.closeTo(6, 0) as any,
        },
      ],
    },
  },
  {
    filename: 'engine-start.h264.aac-mono.mkv',
    expectedMediaInfo: {
      bytesRead: 3841,
      parser: 'media-utils',
      container: 'mkv',
      containerDetail: 'matroska',
      durationInSeconds: expect.closeTo(6, 0) as any,
      videoStreams: [
        {
          codec: 'h264',
          codecDetail: 'V_MPEG4/ISO/AVC',
          durationInSeconds: expect.closeTo(6, 0) as any,
          id: 1,
          width: 1280,
          height: 534,
        },
      ],
      audioStreams: [
        {
          codec: 'aac',
          codecDetail: 'A_AAC',
          durationInSeconds: expect.closeTo(6, 0) as any,
          id: 2,
          sampleRate: 44100,
          channelCount: 1,
          bitsPerSample: 32,
        },
      ],
    },
  },
  {
    filename: 'engine-start.h264.mp3-mono.mkv',
    expectedMediaInfo: {
      bytesRead: 3844,
      parser: 'media-utils',
      container: 'mkv',
      containerDetail: 'matroska',
      durationInSeconds: expect.closeTo(6, 0) as any,
      videoStreams: [
        {
          codec: 'h264',
          codecDetail: 'V_MPEG4/ISO/AVC',
          durationInSeconds: expect.closeTo(6, 0) as any,
          id: 1,
          width: 1280,
          height: 534,
        },
      ],
      audioStreams: [
        {
          codec: 'mp3',
          codecDetail: 'A_MPEG/L3',
          durationInSeconds: expect.closeTo(6, 0) as any,
          id: 2,
          sampleRate: 44100,
          channelCount: 1,
          bitsPerSample: 32,
        },
      ],
    },
  },
  {
    filename: 'engine-start.vp9.opus-mono.webm',
    expectedMediaInfo: {
      bytesRead: 1232,
      parser: 'media-utils',
      container: 'webm',
      containerDetail: 'webm',
      durationInSeconds: expect.closeTo(6, 0) as any,
      videoStreams: [
        {
          codec: 'vp9',
          codecDetail: 'V_VP9',
          durationInSeconds: expect.closeTo(6, 0) as any,
          id: 1,
          width: 1280,
          height: 534,
        },
      ],
      audioStreams: [
        {
          codec: 'opus',
          codecDetail: 'A_OPUS',
          durationInSeconds: expect.closeTo(6, 0) as any,
          id: 2,
          sampleRate: 48000,
          channelCount: 1,
          bitsPerSample: 32,
        },
      ],
    },
  },
  {
    filename: 'engine-start.mjpeg.pcms16le.avi',
    expectedMediaInfo: {
      bytesRead: 8912,
      parser: 'media-utils',
      container: 'avi',
      containerDetail: 'avi',
      durationInSeconds: expect.closeTo(6, 0) as any,
      videoStreams: [
        {
          codec: 'mjpeg',
          codecDetail: 'MJPG',
          id: 1,
          width: 1280,
          height: 534,
          durationInSeconds: expect.closeTo(6, 0) as any,
          fps: expect.closeTo(24, 1) as any,
        },
      ],
      audioStreams: [
        {
          codec: 'pcm_s16le',
          codecDetail: 'pcm_s16le',
          id: 2,
          channelCount: 2,
          sampleRate: 44100,
          bitsPerSample: 16,
          bitrate: 44100 * 2 * 16, // ≈ 1.4 Mbps raw PCM
          durationInSeconds: expect.closeTo(6, 0) as any,
          codecDetails: {
            blockAlign: 4,
            formatTag: 1,
            samplesPerBlock: undefined,
          },
        },
      ],
    },
  },
  {
    filename: 'engine-start.h264.pcms16le.avi',
    expectedMediaInfo: {
      bytesRead: 8912,
      parser: 'media-utils',
      container: 'avi',
      containerDetail: 'avi',
      durationInSeconds: expect.closeTo(6, 0) as any,
      videoStreams: [
        {
          codec: 'h264',
          codecDetail: 'H264',
          id: 1,
          width: 1280,
          height: 534,
          durationInSeconds: expect.closeTo(6, 0) as any,
          fps: expect.closeTo(24, 1) as any,
        },
      ],
      audioStreams: [
        {
          codec: 'pcm_s16le',
          codecDetail: 'pcm_s16le',
          id: 2,
          channelCount: 2,
          sampleRate: 44100,
          bitsPerSample: 16,
          bitrate: 44100 * 2 * 16,
          durationInSeconds: expect.closeTo(6, 0) as any,
          codecDetails: {
            blockAlign: 4,
            formatTag: 1,
            samplesPerBlock: undefined,
          },
        },
      ],
    },
  },
  {
    filename: 'engine-start.h264.mp3-mono.avi',
    expectedMediaInfo: {
      bytesRead: 8968,
      parser: 'media-utils',
      container: 'avi',
      containerDetail: 'avi',
      durationInSeconds: expect.closeTo(6, 0) as any,
      videoStreams: [
        {
          codec: 'h264',
          codecDetail: 'H264',
          durationInSeconds: expect.closeTo(6, 0) as any,
          id: 1,
          width: 1280,
          height: 534,
          fps: 24,
        },
      ],
      audioStreams: [
        {
          codec: 'mp3',
          codecDetail: 'mp3',
          durationInSeconds: expect.closeTo(6, 0) as any,
          id: 2,
          sampleRate: 44100,
          channelCount: 1,
          bitrate: 0,
          bitsPerSample: undefined,
          codecDetails: {
            formatTag: 85,
            blockAlign: 1152,
            samplesPerBlock: undefined,
          },
        },
      ],
    },
  },
  {
    filename: 'engine-start.mpeg2video.mp2.m2ts',
    expectedMediaInfo: {
      bytesRead: 65536,
      parser: 'media-utils',
      container: 'mpegts',
      containerDetail: 'mpegts',
      videoStreams: [
        {
          id: 256,
          codec: 'mpeg2video',
          width: 1280,
          height: 534,
          fps: expect.closeTo(24, 1) as any,
        },
      ],
      audioStreams: [
        {
          id: 257,
          codec: 'mp2',
          codecDetail: 'MPEG-1 Layer II',
          channelCount: 2,
          sampleRate: 44100,
          bitrate: 384000,
          codecDetails: {
            layer: 2,
            padding: 0,
          },
          language: 'eng',
        },
      ],
    },
  },
  {
    filename: 'engine-start.h264.aac-mono.m2ts',
    expectedMediaInfo: {
      bytesRead: 65536,
      parser: 'media-utils',
      container: 'mpegts',
      containerDetail: 'mpegts',
      videoStreams: [
        {
          codec: 'h264',
          codecDetail: 'avc1.64001f',
          id: 4113,
          width: 1280,
          height: 534,
        },
      ],
      audioStreams: [
        {
          codec: 'aac',
          id: 4352,
          sampleRate: 44100,
          channelCount: 1,
          codecDetail: 'AAC in ADTS',
          language: 'eng',
        },
      ],
    },
  },
  {
    filename: 'engine-start.wmv2.wmav2.wmv',
    expectedMediaInfo: {
      bytesRead: 65536,
      parser: 'media-utils',
      container: 'asf',
      containerDetail: 'wmv',
      durationInSeconds: expect.closeTo(6, 0) as any,
      videoStreams: [
        {
          id: 1,
          codec: 'wmv2',
          codecDetail: 'WMV2',
          width: 1280,
          height: 534,
          durationInSeconds: expect.closeTo(6, 0) as any,
          fps: undefined,
        },
      ],
      audioStreams: [
        {
          id: 2,
          codec: 'wmav2',
          codecDetail: 'WMAv2',
          channelCount: 2,
          sampleRate: 44100,
          bitrate: 128000,
          bitsPerSample: 16,
          durationInSeconds: expect.closeTo(6, 0) as any,
        },
      ],
      fileProperties: expect.any(Object) as any,
      additionalStreamInfo: expect.any(Map) as any,
    },
  },
  {
    filename: 'engine-start.opus.ogg',
    expectedMediaInfo: {
      bytesRead: 65536,
      parser: 'media-utils',
      container: 'ogg',
      containerDetail: 'ogg',
      durationInSeconds: undefined,
      videoStreams: [],
      audioStreams: [
        {
          id: 1,
          codec: 'opus',
          codecDetail: 'opus',
          channelCount: 2,
          sampleRate: 48000,
          durationInSeconds: undefined,
        },
      ],
    },
  },
  {
    filename: 'engine-start.vorbis.ogg',
    expectedMediaInfo: {
      bytesRead: 65536,
      parser: 'media-utils',
      container: 'ogg',
      containerDetail: 'ogg',
      durationInSeconds: undefined,
      videoStreams: [],
      audioStreams: [
        {
          id: 1,
          codec: 'vorbis',
          codecDetail: 'vorbis',
          channelCount: 2,
          sampleRate: 48000,
          durationInSeconds: undefined,
        },
      ],
    },
  },
  {
    filename: 'engine-start.wmav2.wma',
    expectedMediaInfo: {
      bytesRead: 65536,
      parser: 'media-utils',
      container: 'asf',
      containerDetail: 'wma',
      durationInSeconds: expect.closeTo(6, 0) as any,
      videoStreams: [],
      audioStreams: [
        {
          id: 1,
          codec: 'wmav2',
          codecDetail: 'WMAv2',
          channelCount: 2,
          sampleRate: 44100,
          bitrate: 128000,
          bitsPerSample: 16,
          durationInSeconds: expect.closeTo(6, 0) as any,
        },
      ],
      additionalStreamInfo: expect.any(Map) as any,
      fileProperties: expect.any(Object) as any,
    },
  },
  {
    filename: 'engine-start.pcms16le.wav',
    expectedMediaInfo: {
      bytesRead: 65536,
      parser: 'media-utils',
      container: 'wav',
      containerDetail: 'wav',
      durationInSeconds: expect.closeTo(6, 0) as any,
      videoStreams: [],
      audioStreams: [
        {
          id: 1,
          codec: 'pcm_s16le',
          codecDetail: 'pcm_s16le',
          channelCount: 2,
          sampleRate: 44100,
          bitsPerSample: 16,
          bitrate: 44100 * 2 * 16,
          durationInSeconds: expect.closeTo(6, 0) as any,
          codecDetails: {
            blockAlign: 4,
            formatTag: 1,
            samplesPerBlock: undefined,
          },
        },
      ],
    },
  },
];
